name: Update AdBlock Rules Every 24 Hours
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule: 
    - cron:  '0 0 */1 * *' 

jobs:
  update-adblock-rules-then-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.0.0
            
      - name: Adguard Simplified Domain Names Filter
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
          file-name: AdGuard-Simplified-Domain-Names-Filter.txt
    
      - name: EasyList
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://easylist-downloads.adblockplus.org/easylist.txt
          file-name: Easylist.txt
          
      - name: EasyList China
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://easylist-downloads.adblockplus.org/easylistchina.txt
          file-name: Easylist-China.txt

      - name: EasyList Privacy
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://easylist.to/easylist/easyprivacy.txt
          file-name: Easylist-Privacy.txt
      
      - name: I dont care about cookies
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://www.i-dont-care-about-cookies.eu/abp/
          file-name: I-dont-care-about-cookies.txt     
      
      - name: AdAway default blocklist
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://adaway.org/hosts.txt
          file-name: AdAway-default-blocklist.txt

      - name: CJX annoyance
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          file-name: CJX-annoyance.txt
      
      - name: Commit Changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
              exit 0
          else 
              git add .
              git config --local user.email "81902114+SoraJinBot@users.noreply.github.com"
              git config --local user.name "SoraJinBot"
              git commit -m "Updated at $(date)" -a
          fi
            
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge CDN Cache
        run: curl ${{ secrets.CDN_URL }}
